name: Deploy Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: web

    steps:
      - name: Install Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions-bot'
          git config --global user.email 'support+actions@github.com'
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Deploy
        run: npm run deploy